---
title: blog.kfuji.net
timezone: America/Los_Angeles
collections:
  authors:
    title: Authors
    output: true
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: categories
  values:
    layout: category
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
theme: jekyll-theme-hacker
description: KirinFuji's Blog
google_analytics: UA-154872147-1
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
