---
title: blog.kfuji.net
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  categories2:
    title: Categories2
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: Categories2
  values:
    layout: category2
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
theme: jekyll-theme-hacker
description: KirinFuji's Blog
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
